;; rocq_shims.wat — wasm_of_ocaml runtime module supplying the custom C
;; primitives the natively-built rocq-runtime references but the wasm_of_ocaml
;; runtime does not provide. Passed to `wasm_of_ocaml compile` as a runtime
;; file; the compiler assigns it module name "env" and binaryen merges it into
;; the runtime, so these exports satisfy the wasm `env.*` imports. (A JS
;; //Provides fragment does NOT satisfy a wasm C-primitive import — wasm_of_ocaml
;; resolves them from the wasm runtime only, verified this session.)  See BACKEND.md.
;;
;; ABI: OCaml values are (ref eq); ints are (ref.i31 n); a boxed float is a
;; (struct (field f64)) — identical to the runtime's $float so binaryen's type
;; canonicalisation unifies them.  Zarith Z.t: a "small" value is (ref.i31 n);
;; a "big" value is a JS BigInt wrapped by the runtime's `wrap`.  All zarith
;; arithmetic delegates to JS BigInt helpers (globalThis.rocqz_*, imported from
;; the "js" module which wasm_of_ocaml binds to globalThis) — see web/rocq_zarith.js.
(module
   (type $float (struct (field f64)))
   (type $block (array (mut (ref eq))))

   ;; runtime helpers (exports of the merged runtime, module "env")
   (import "env" "wrap"   (func $wrap   (param anyref)   (result (ref eq))))
   (import "env" "unwrap" (func $unwrap (param (ref eq)) (result anyref)))
   (import "env" "caml_copy_int64" (func $copy_i64 (param i64) (result (ref eq))))
   (import "env" "Int64_val"       (func $i64_val (param (ref eq)) (result i64)))
   (import "env" "caml_jsstring_of_string" (func $js_of_str (param (ref eq)) (result (ref eq))))
   (import "env" "caml_string_of_jsstring" (func $str_of_js (param (ref eq)) (result (ref eq))))
   (import "env" "caml_failwith" (func $failwith (param (ref eq))))

   ;; JS BigInt backend (globalThis.rocqz_*, via the "js" import module)
   (import "js" "rocqz_of_int"   (func $z_of_int   (param i32)    (result anyref)))
   (import "js" "rocqz_is_small" (func $z_is_small (param anyref) (result i32)))
   (import "js" "rocqz_to_int_"  (func $z_to_int   (param anyref) (result i32)))
   (import "js" "rocqz_neg"  (func $z_neg  (param anyref) (result anyref)))
   (import "js" "rocqz_abs"  (func $z_abs  (param anyref) (result anyref)))
   (import "js" "rocqz_succ" (func $z_succ (param anyref) (result anyref)))
   (import "js" "rocqz_pred" (func $z_pred (param anyref) (result anyref)))
   (import "js" "rocqz_lognot" (func $z_lognot (param anyref) (result anyref)))
   (import "js" "rocqz_add" (func $z_add (param anyref anyref) (result anyref)))
   (import "js" "rocqz_sub" (func $z_sub (param anyref anyref) (result anyref)))
   (import "js" "rocqz_mul" (func $z_mul (param anyref anyref) (result anyref)))
   (import "js" "rocqz_div" (func $z_div (param anyref anyref) (result anyref)))
   (import "js" "rocqz_rem" (func $z_rem (param anyref anyref) (result anyref)))
   (import "js" "rocqz_cdiv" (func $z_cdiv (param anyref anyref) (result anyref)))
   (import "js" "rocqz_fdiv" (func $z_fdiv (param anyref anyref) (result anyref)))
   (import "js" "rocqz_divexact" (func $z_divexact (param anyref anyref) (result anyref)))
   (import "js" "rocqz_gcd" (func $z_gcd (param anyref anyref) (result anyref)))
   (import "js" "rocqz_logand" (func $z_logand (param anyref anyref) (result anyref)))
   (import "js" "rocqz_logor"  (func $z_logor  (param anyref anyref) (result anyref)))
   (import "js" "rocqz_logxor" (func $z_logxor (param anyref anyref) (result anyref)))
   (import "js" "rocqz_shift_left"  (func $z_shl (param anyref i32) (result anyref)))
   (import "js" "rocqz_shift_right" (func $z_shr (param anyref i32) (result anyref)))
   (import "js" "rocqz_pow" (func $z_pow (param anyref i32) (result anyref)))
   (import "js" "rocqz_testbit" (func $z_testbit (param anyref i32) (result i32)))
   (import "js" "rocqz_sign"    (func $z_sign (param anyref) (result i32)))
   (import "js" "rocqz_compare" (func $z_compare (param anyref anyref) (result i32)))
   (import "js" "rocqz_equal"   (func $z_equal (param anyref anyref) (result i32)))
   (import "js" "rocqz_of_i64"  (func $z_of_i64 (param i64) (result anyref)))
   (import "js" "rocqz_to_i64"  (func $z_to_i64 (param anyref) (result i64)))
   (import "js" "rocqz_of_substring_base"
      (func $z_of_substr (param i32) (param anyref) (param i32) (param i32) (result anyref)))
   (import "js" "rocqz_format" (func $z_format (param anyref) (param anyref) (result anyref)))
   (import "js" "rocqz_overflow_msg" (func $z_ovf (result anyref)))

   (func $Double_val (param $v (ref eq)) (result f64)
      (struct.get $float 0 (ref.cast (ref $float) (local.get $v))))
   (func $copy_double (param $x f64) (result (ref eq))
      (struct.new $float (local.get $x)))
   (func $unit (result (ref eq)) (ref.i31 (i32.const 0)))

   ;; Z.t (ref eq) -> JS BigInt (anyref): small int -> BigInt, else unwrap
   (func $z_arg (param $v (ref eq)) (result anyref)
      (if (result anyref) (ref.test (ref i31) (local.get $v))
         (then (call $z_of_int (i31.get_s (ref.cast (ref i31) (local.get $v)))))
         (else (call $unwrap (local.get $v)))))
   ;; JS BigInt (anyref) -> Z.t (ref eq): normalise to small i31 when it fits
   (func $z_ret (param $b anyref) (result (ref eq))
      (if (result (ref eq)) (i32.eqz (call $z_is_small (local.get $b)))
         (then (call $wrap (local.get $b)))
         (else (ref.i31 (call $z_to_int (local.get $b))))))
   (func $arg_i (param $v (ref eq)) (result i32)
      (i31.get_s (ref.cast (ref i31) (local.get $v))))

   ;; ---- Float64 (kernel/float64_31.ml externals; IEEE self-test at init) ----
   (func (export "rocq_fadd_byte") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq))
      (call $copy_double (f64.add (call $Double_val (local.get $a)) (call $Double_val (local.get $b)))))
   (func (export "rocq_fsub_byte") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq))
      (call $copy_double (f64.sub (call $Double_val (local.get $a)) (call $Double_val (local.get $b)))))
   (func (export "rocq_fmul_byte") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq))
      (call $copy_double (f64.mul (call $Double_val (local.get $a)) (call $Double_val (local.get $b)))))
   (func (export "rocq_fdiv_byte") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq))
      (call $copy_double (f64.div (call $Double_val (local.get $a)) (call $Double_val (local.get $b)))))
   (func (export "rocq_fsqrt_byte") (param $a (ref eq)) (result (ref eq))
      (call $copy_double (f64.sqrt (call $Double_val (local.get $a)))))
   (func $next_up (param $f f64) (result f64)
      (local $b i64)
      (if (f64.ne (local.get $f) (local.get $f)) (then (return (local.get $f))))
      (if (f64.eq (local.get $f) (f64.const inf)) (then (return (local.get $f))))
      (if (f64.eq (local.get $f) (f64.const 0)) (then (return (f64.const 5e-324))))
      (local.set $b (i64.reinterpret_f64 (local.get $f)))
      (if (f64.gt (local.get $f) (f64.const 0))
         (then (local.set $b (i64.add (local.get $b) (i64.const 1))))
         (else (local.set $b (i64.sub (local.get $b) (i64.const 1)))))
      (f64.reinterpret_i64 (local.get $b)))
   (func (export "rocq_next_up_byte") (param $a (ref eq)) (result (ref eq))
      (call $copy_double (call $next_up (call $Double_val (local.get $a)))))
   (func (export "rocq_next_down_byte") (param $a (ref eq)) (result (ref eq))
      (call $copy_double (f64.neg (call $next_up (f64.neg (call $Double_val (local.get $a)))))))

   ;; ---- threads.posix: single-threaded no-ops ----
   (func (export "caml_thread_initialize") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "caml_thread_id") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "caml_thread_self") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "caml_thread_new") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "caml_thread_join") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "caml_thread_yield") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "caml_thread_cleanup") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "caml_thread_uncaught_exception") (param (ref eq)) (result (ref eq)) (call $unit))

   ;; ---- getpid ----
   (func (export "caml_unix_getpid") (param (ref eq)) (result (ref eq)) (ref.i31 (i32.const 42)))

   ;; ---- VM init-time tcode plumbing (vm:false -> only module-init producers) ----
   (func (export "init_rocq_vm") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "rocq_accumulate") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "rocq_makeaccu") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "rocq_offset_tcode") (param $tc (ref eq)) (param (ref eq)) (result (ref eq)) (local.get $tc))
   (func (export "rocq_set_bytecode_field") (param (ref eq)) (param (ref eq)) (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "rocq_pushpop") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "rocq_curry2_1_addr") (param (ref eq)) (result (ref eq)) (call $unit))

   ;; ---- zarith (delegates to JS BigInt; see web/rocq_zarith.js) ----
   (func (export "ml_z_init") (param (ref eq)) (result (ref eq)) (call $unit))
   (func (export "ml_z_neg")  (param $a (ref eq)) (result (ref eq)) (call $z_ret (call $z_neg  (call $z_arg (local.get $a)))))
   (func (export "ml_z_abs")  (param $a (ref eq)) (result (ref eq)) (call $z_ret (call $z_abs  (call $z_arg (local.get $a)))))
   (func (export "ml_z_succ") (param $a (ref eq)) (result (ref eq)) (call $z_ret (call $z_succ (call $z_arg (local.get $a)))))
   (func (export "ml_z_pred") (param $a (ref eq)) (result (ref eq)) (call $z_ret (call $z_pred (call $z_arg (local.get $a)))))
   (func (export "ml_z_lognot") (param $a (ref eq)) (result (ref eq)) (call $z_ret (call $z_lognot (call $z_arg (local.get $a)))))
   (func (export "ml_z_add") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_add (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_sub") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_sub (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_mul") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_mul (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_div") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_div (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_rem") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_rem (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_cdiv") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_cdiv (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_fdiv") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_fdiv (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_divexact") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_divexact (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_gcd") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_gcd (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_logand") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_logand (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_logor")  (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_logor  (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_logxor") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (call $z_ret (call $z_logxor (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_shift_left")  (param $a (ref eq)) (param $n (ref eq)) (result (ref eq)) (call $z_ret (call $z_shl (call $z_arg (local.get $a)) (call $arg_i (local.get $n)))))
   (func (export "ml_z_shift_right") (param $a (ref eq)) (param $n (ref eq)) (result (ref eq)) (call $z_ret (call $z_shr (call $z_arg (local.get $a)) (call $arg_i (local.get $n)))))
   (func (export "ml_z_shift_right_trunc") (param $a (ref eq)) (param $n (ref eq)) (result (ref eq)) (call $z_ret (call $z_shr (call $z_arg (local.get $a)) (call $arg_i (local.get $n)))))
   (func (export "ml_z_pow") (param $a (ref eq)) (param $n (ref eq)) (result (ref eq)) (call $z_ret (call $z_pow (call $z_arg (local.get $a)) (call $arg_i (local.get $n)))))
   (func (export "ml_z_testbit") (param $a (ref eq)) (param $n (ref eq)) (result (ref eq)) (ref.i31 (call $z_testbit (call $z_arg (local.get $a)) (call $arg_i (local.get $n)))))
   (func (export "ml_z_sign")    (param $a (ref eq)) (result (ref eq)) (ref.i31 (call $z_sign (call $z_arg (local.get $a)))))
   (func (export "ml_z_compare") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (ref.i31 (call $z_compare (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_equal")   (param $a (ref eq)) (param $b (ref eq)) (result (ref eq)) (ref.i31 (call $z_equal (call $z_arg (local.get $a)) (call $z_arg (local.get $b)))))
   (func (export "ml_z_mul_overflows") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq))
      (local $p i64)
      (local.set $p (i64.mul (i64.extend_i32_s (call $arg_i (local.get $a)))
                             (i64.extend_i32_s (call $arg_i (local.get $b)))))
      (ref.i31 (i32.or (i64.gt_s (local.get $p) (i64.const 0x3FFFFFFF))
                       (i64.lt_s (local.get $p) (i64.const -0x40000000)))))
   (func (export "ml_z_div_rem") (param $a (ref eq)) (param $b (ref eq)) (result (ref eq))
      (local $x anyref) (local $y anyref)
      (local.set $x (call $z_arg (local.get $a)))
      (local.set $y (call $z_arg (local.get $b)))
      (array.new_fixed $block 3
         (ref.i31 (i32.const 0))
         (call $z_ret (call $z_div (local.get $x) (local.get $y)))
         (call $z_ret (call $z_rem (local.get $x) (local.get $y)))))
   (func (export "ml_z_of_int64") (param $a (ref eq)) (result (ref eq)) (call $z_ret (call $z_of_i64 (call $i64_val (local.get $a)))))
   (func (export "ml_z_to_int64") (param $a (ref eq)) (result (ref eq)) (call $copy_i64 (call $z_to_i64 (call $z_arg (local.get $a)))))
   (func (export "ml_z_to_int") (param $a (ref eq)) (result (ref eq))
      (local $b anyref)
      (local.set $b (call $z_arg (local.get $a)))
      (if (result (ref eq)) (call $z_is_small (local.get $b))
         (then (ref.i31 (call $z_to_int (local.get $b))))
         (else (call $failwith (call $str_of_js (call $wrap (call $z_ovf)))) (call $unit))))
   (func (export "ml_z_of_substring_base") (param $base (ref eq)) (param $s (ref eq)) (param $pos (ref eq)) (param $len (ref eq)) (result (ref eq))
      (call $z_ret (call $z_of_substr
         (call $arg_i (local.get $base)) (call $unwrap (call $js_of_str (local.get $s)))
         (call $arg_i (local.get $pos)) (call $arg_i (local.get $len)))))
   (func (export "ml_z_format") (param $fmt (ref eq)) (param $z (ref eq)) (result (ref eq))
      (call $str_of_js (call $wrap (call $z_format (call $unwrap (call $js_of_str (local.get $fmt))) (call $z_arg (local.get $z))))))

)
