(* web_check.ml — the REAL browser seam.

   This is the js_of_ocaml entry point that exposes the whole rocq-comparator
   pipeline to JavaScript as the frozen `window.RocqComparator` contract
   (BACKEND.md section 6). It reuses the core `rocq_comparator` library
   unchanged:

     - Config.of_json   : parse the request's config (same schema as the CLI)
     - Check.run_inner  : the entire in-process pipeline
     - Filter / Assumptions / Compare (via Check) / Envcheck / Shadowing : the
       real kernel-level checks, wired here as *browser hooks*
     - Verdict.to_string: the JSON verdict returned to JS

   Browser hooks differ from the CLI's `real_hooks` (bin/main.ml) only in the
   two ways the browser forces: rocqchk = None (no subprocess) and no OS
   sandbox (the browser origin is the sandbox). Everything else is identical,
   so the guarantees are the same.

   EXECUTION: built through js_of_ocaml against the coerce-32bit OCAMLPATH
   overlay produced by web/build-real.sh (a patched, Int64-backed rocq-runtime
   kernel.cma, uint63_31/float64_31), the emitted JS actually RUNS a real Rocq
   check in the browser / node — the kernel's `Sys.word_size = 64` assert
   (kernel/uint63_63.ml) is gone. Built against the stock native rocq-runtime it
   instead traps at startup on that assert. The only remaining limitation is the
   prelude: no Corelib `.vo` bundle ships yet (native `.vo` fail to unmarshal
   under jsoo — "integer too large" — and must be regenerated by a patched
   compiler), so checks run with `-noinit` (core Gallina only). See BACKEND.md
   sections 1c-3. *)

open Js_of_ocaml
module C = Rocq_comparator

(* ---- JS Promise / Error helpers (no ppx, just Js.Unsafe) ---- *)

let promise_resolve (v : _) : _ = Js.Unsafe.(fun_call (js_expr "Promise.resolve") [| inject v |])
let promise_reject (v : _) : _ = Js.Unsafe.(fun_call (js_expr "Promise.reject") [| inject v |])
let js_error (msg : string) = Js.Unsafe.(new_obj (js_expr "Error") [| inject (Js.string msg) |])

(* ---- browser hooks: real checks, no rocqchk, no sandbox ---- *)

let browser_hooks () : C.Check.hooks =
  { C.Check.filter =
      (fun ~strict ~permitted_plugins ~permitted_libraries vc ->
         C.Filter.check
           { C.Filter.mode = (if strict then C.Filter.Strict else C.Filter.Lenient);
             permitted_plugins; permitted_libraries }
           vc);
    assumptions = C.Assumptions.check;
    envcheck = C.Envcheck.check;
    trusted_roots = C.Envcheck.trusted_roots;
    rocqchk = None;
    (* the strict AST filter runs, so the verdict is a normal one *)
    filter_status = C.Verdict.Ok }

(* ---- write the request's inline files into the js_of_ocaml pseudo-FS ---- *)

(* The browser has no OS filesystem. The request carries the two .v sources (and
   any loadpath files) inline; Config points at their VFS paths. We do NOT
   change the core Config to accept inline source: instead we materialise the
   files here and let Config/Driver read them exactly as on disk. *)
let write_files (files : Yojson.Safe.t) : unit =
  let put path content =
    (try Sys_js.create_file ~name:path ~content
     with _ -> (try Sys_js.update_file ~name:path ~content with _ -> ()))
  in
  match files with
  | `Assoc l ->
    List.iter (fun (path, v) -> match v with `String s -> put path s | _ -> ()) l
  | _ -> ()

(* ---- one-time VFS/environment setup for the browser Rocq runtime ----

   A natively-built Rocq initialises findlib (ocamlfind) at startup to be able
   to [Declare ML Module] plugins. findlib reads a [findlib.conf]; in the jsoo
   pseudo-FS the working directory is [/static] and no such file exists, so the
   runtime raises "Config file not found ... /static/findlib.conf". We drop a
   minimal findlib.conf into the VFS so findlib initialises cleanly. No ML
   modules are ever dynamically loaded in the browser (ltac and friends are
   statically linked), so the paths only need to exist, not resolve packages. *)
let vfs_ready = ref false
let setup_vfs () =
  if not !vfs_ready then begin
    vfs_ready := true;
    let put path content =
      (try Sys_js.create_file ~name:path ~content
       with _ -> (try Sys_js.update_file ~name:path ~content with _ -> ()))
    in
    (* findlib config: destdir/path just need to be present strings *)
    put "/static/findlib.conf" "destdir=\"/static/lib\"\npath=\"/static/lib\"\nldconf=\"ignore\"\nsystem=\"\"\n";
    put "/static/lib/.keep" "";
    (* Rocq's native [Control.timeout] arms a Unix interval timer (setitimer +
       SIGALRM) which does not exist in the browser. Replace it with a trivial
       run-to-completion implementation: the in-worker [timeout_s] becomes
       best-effort and the HARD wall-clock cap is enforced by the worker glue
       terminating the Web Worker (BACKEND.md section 6, "hard timeout"). This
       is the runtime equivalent of wacoq/coq-lsp's timeout-trampoline patch,
       done through the public [Control.set_timeout] hook so no rocq-runtime
       source change is needed. *)
    Control.set_timeout { Control.timeout = (fun _n f x -> Ok (f x)) }
  end

let version () = C.Driver.rocq_version ()

let with_version (v : C.Verdict.t) = { v with C.Verdict.rocq_version = version () }

(* ---- one check: request JSON string -> (verdict JSON, out-of-band error) ---- *)

let run_check_string (req : string) : (string, string) result =
  match Yojson.Safe.from_string req with
  | exception Yojson.Json_error m -> Error ("malformed request JSON: " ^ m)
  | j ->
    let member k = match j with `Assoc l -> List.assoc_opt k l | _ -> None in
    (match member "config" with
     | None | Some `Null -> Error "malformed request JSON: missing \"config\" object"
     | Some cfg_json ->
       let files = match member "files" with Some (`Assoc _ as a) -> a | _ -> `Assoc [] in
       write_files files;
       (* Config resolves relative challenge/solution/loadpath paths against
          [config_dir]. In the jsoo pseudo-FS the working directory is the fake
          device root (/static); [write_files] materialises the inline files
          there, so [config_dir] must be that same directory for the resolved
          paths to hit the files we just wrote. *)
       (match C.Config.of_json ~config_dir:(Sys.getcwd ()) cfg_json with
        | Result.Error m ->
          (* config validation failure is a normal, resolved verdict *)
          Ok (C.Verdict.to_string (with_version (C.Verdict.fail C.Verdict.Config_error m)))
        | Result.Ok cfg0 ->
          (* the browser forces these two regardless of what the request said *)
          let cfg =
            { cfg0 with C.Config.rocqchk = false; vm = false; sandbox = C.Config.No_sandbox }
          in
          (* scratch is only ever used by the rocqchk hook, which is None here *)
          let v = C.Check.run_inner (browser_hooks ()) cfg ~scratch:"/scratch" in
          Ok (C.Verdict.to_string v)))

let run_check (req : Js.js_string Js.t) =
  match run_check_string (Js.to_string req) with
  | Ok verdict_json -> promise_resolve (Js.string verdict_json)
  | Error oob -> promise_reject (js_error oob)
  | exception e ->
    (* an unexpected OCaml exception is reported as an internal_error verdict
       (resolved), never as an out-of-band rejection *)
    promise_resolve
      (Js.string
         (C.Verdict.to_string
            (with_version (C.Verdict.fail C.Verdict.Internal_error (Printexc.to_string e)))))

(* ---- ready: resolves as soon as the module is loaded ----

   In the real WASM build the expensive work (fetching the wasm runtime and the
   prelude .vo bundle into the worker FS) happens in the worker glue BEFORE this
   OCaml module runs, so by the time this code executes the runtime is present.
   `Driver.init` is idempotent and is run lazily by the first `check`
   (Check.run_inner calls it); the first check's loadpath is the one that sticks
   for the worker's lifetime. To change the loadpath, the main thread respawns
   the worker (which re-runs this module). *)
let ready = promise_resolve Js.undefined

let () =
  setup_vfs ();
  let comparator =
    Js.Unsafe.obj
      [| ("ready", Js.Unsafe.inject ready);
         ("version", Js.Unsafe.inject (Js.string (version ())));
         ("check", Js.Unsafe.inject (Js.wrap_callback (fun req -> run_check req))) |]
  in
  Js.Unsafe.set Js.Unsafe.global (Js.string "RocqComparator") comparator
